### ISSUE TITLE
Can it be used with Python3?

### ISSUE THREAD

**Issue by zwbzzp** [aluzzardi/wssh#20]
I want to use it with Python3.If it can be supported by Python3, that's great!

**Comment by sorgloomer** [comment]
Hey @zwbzzp ! I just implemented a similar project based on wssh to support my needs. It's written in python3, check it out: https://github.com/sorgloomer/websocket_terminal

**Comment by tartavull** [comment]
```
Traceback (most recent call last):
  File "/Users/itq/miniconda3/bin/wsshd", line 4, in <module>
    __import__('pkg_resources').run_script('wssh==0.1.0', 'wsshd')
  File "/Users/itq/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/itq/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1445, in run_script
    code = compile(source, script_filename, 'exec')
  File "/Users/itq/miniconda3/lib/python3.7/site-packages/wssh-0.1.0-py3.7.egg/EGG-INFO/scripts/wsshd", line 97
    print '{0} running on {1}:{2}'.format(agent, args.host, args.port)
```
it doesn't look like

**Comment by glensc** [comment]
https://github.com/aluzzardi/wssh/pull/17

**Comment by glensc** [comment]
@sorgloomer your version also doesn't run with the latest python3:
- https://github.com/sorgloomer/websocket_terminal/issues/7
