### ISSUE TITLE
TypeError: from_buffer() cannot return the address of the raw string within a str or unicode or bytearray object

### ISSUE THREAD

**Issue by Ericwtl** [aluzzardi/wssh#34]
After start wssd on linux terminal，login linux by browser, and click the connect button, below appeared:

Error: from_buffer() cannot return the address of the raw string within a str or
 unicode or bytearray object                                                    
Connection Reset By peer.

logs:
--------------------------------------------------------------------------------
DEBUG in wsshd [/usr/lib/python2.7/site-packages/wssh-0.1.0-py2.7.egg/EGG-INFO/scripts/wsshd:27]:
192.168.1.115 -> root@localhost: [interactive shell]
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
ERROR in wsshd [/usr/lib/python2.7/site-packages/wssh-0.1.0-py2.7.egg/EGG-INFO/scripts/wsshd:47]:
Error while connecting to localhost: from_buffer() cannot return the address of the raw string within a str or unicode or bytearray object
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/wssh-0.1.0-py2.7.egg/EGG-INFO/scripts/wsshd", line 44, in connect
    allow_agent=app.config.get('WSSH_ALLOW_SSH_AGENT', False))
  File "/usr/lib/python2.7/site-packages/wssh-0.1.0-py2.7.egg/wssh/server.py", line 98, in open
    look_for_keys=False)
  File "/usr/lib/python2.7/site-packages/paramiko/client.py", line 380, in connect
    look_for_keys, gss_auth, gss_kex, gss_deleg_creds, gss_host)
  File "/usr/lib/python2.7/site-packages/paramiko/client.py", line 608, in _auth
    self._transport.auth_password(username, password)
  File "/usr/lib/python2.7/site-packages/paramiko/transport.py", line 1266, in auth_password
    self.auth_handler.auth_password(username, password, my_event)
  File "/usr/lib/python2.7/site-packages/paramiko/auth_handler.py", line 107, in auth_password
    self._request_auth()
  File "/usr/lib/python2.7/site-packages/paramiko/auth_handler.py", line 158, in _request_auth
    self.transport._send_message(m)
  File "/usr/lib/python2.7/site-packages/paramiko/transport.py", line 1587, in _send_message
    self.packetizer.send_message(data)
  File "/usr/lib/python2.7/site-packages/paramiko/packet.py", line 360, in send_message
    out = self.__block_engine_out.update(packet)
  File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/primitives/ciphers/base.py", line 149, in update
    return self._ctx.update(data)
  File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/backends/openssl/ciphers.py", line 120, in update
    n = self.update_into(data, buf)
  File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/backends/openssl/ciphers.py", line 131, in update_into
    "unsigned char *", self._backend._ffi.from_buffer(buf)
TypeError: from_buffer() cannot return the address of the raw string within a str or unicode or bytearray object
--------------------------------------------------------------------------------
DEBUG in wsshd [/usr/lib/python2.7/site-packages/wssh-0.1.0-py2.7.egg/EGG-INFO/scripts/wsshd:27]:
192.168.1.115 -> root@127.0.0.1: [interactive shell]
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
ERROR in wsshd [/usr/lib/python2.7/site-packages/wssh-0.1.0-py2.7.egg/EGG-INFO/scripts/wsshd:47]:
Error while connecting to 127.0.0.1: from_buffer() cannot return the address of the raw string within a str or unicode or bytearray object
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/wssh-0.1.0-py2.7.egg/EGG-INFO/scripts/wsshd", line 44, in connect
    allow_agent=app.config.get('WSSH_ALLOW_SSH_AGENT', False))
  File "/usr/lib/python2.7/site-packages/wssh-0.1.0-py2.7.egg/wssh/server.py", line 98, in open
    look_for_keys=False)
  File "/usr/lib/python2.7/site-packages/paramiko/client.py", line 380, in connect
    look_for_keys, gss_auth, gss_kex, gss_deleg_creds, gss_host)
  File "/usr/lib/python2.7/site-packages/paramiko/client.py", line 608, in _auth
    self._transport.auth_password(username, password)
  File "/usr/lib/python2.7/site-packages/paramiko/transport.py", line 1266, in auth_password
    self.auth_handler.auth_password(username, password, my_event)
  File "/usr/lib/python2.7/site-packages/paramiko/auth_handler.py", line 107, in auth_password
    self._request_auth()
  File "/usr/lib/python2.7/site-packages/paramiko/auth_handler.py", line 158, in _request_auth
    self.transport._send_message(m)
  File "/usr/lib/python2.7/site-packages/paramiko/transport.py", line 1587, in _send_message
    self.packetizer.send_message(data)
  File "/usr/lib/python2.7/site-packages/paramiko/packet.py", line 360, in send_message
    out = self.__block_engine_out.update(packet)
  File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/primitives/ciphers/base.py", line 149, in update
    return self._ctx.update(data)
  File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/backends/openssl/ciphers.py", line 120, in update
    n = self.update_into(data, buf)
  File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/backends/openssl/ciphers.py", line 131, in update_into
    "unsigned char *", self._backend._ffi.from_buffer(buf)
TypeError: from_buffer() cannot return the address of the raw string within a str or unicode or bytearray object
--------------------------------------------------------------------------------
DEBUG in wsshd [/usr/lib/python2.7/site-packages/wssh-0.1.0-py2.7.egg/EGG-INFO/scripts/wsshd:27]:
192.168.1.115 -> aaronwtl@localhost: [interactive shell]
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
ERROR in wsshd [/usr/lib/python2.7/site-packages/wssh-0.1.0-py2.7.egg/EGG-INFO/scripts/wsshd:47]:
Error while connecting to localhost: from_buffer() cannot return the address of the raw string within a str or unicode or bytearray object
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/wssh-0.1.0-py2.7.egg/EGG-INFO/scripts/wsshd", line 44, in connect
    allow_agent=app.config.get('WSSH_ALLOW_SSH_AGENT', False))
  File "/usr/lib/python2.7/site-packages/wssh-0.1.0-py2.7.egg/wssh/server.py", line 98, in open
    look_for_keys=False)
  File "/usr/lib/python2.7/site-packages/paramiko/client.py", line 380, in connect
    look_for_keys, gss_auth, gss_kex, gss_deleg_creds, gss_host)
  File "/usr/lib/python2.7/site-packages/paramiko/client.py", line 608, in _auth
    self._transport.auth_password(username, password)
  File "/usr/lib/python2.7/site-packages/paramiko/transport.py", line 1266, in auth_password
    self.auth_handler.auth_password(username, password, my_event)
  File "/usr/lib/python2.7/site-packages/paramiko/auth_handler.py", line 107, in auth_password
    self._request_auth()
  File "/usr/lib/python2.7/site-packages/paramiko/auth_handler.py", line 158, in _request_auth
    self.transport._send_message(m)
  File "/usr/lib/python2.7/site-packages/paramiko/transport.py", line 1587, in _send_message
    self.packetizer.send_message(data)
  File "/usr/lib/python2.7/site-packages/paramiko/packet.py", line 360, in send_message
    out = self.__block_engine_out.update(packet)
  File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/primitives/ciphers/base.py", line 149, in update
    return self._ctx.update(data)
  File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/backends/openssl/ciphers.py", line 120, in update
    n = self.update_into(data, buf)
  File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/backends/openssl/ciphers.py", line 131, in update_into
    "unsigned char *", self._backend._ffi.from_buffer(buf)
TypeError: from_buffer() cannot return the address of the raw string within a str or unicode or bytearray object
--------------------------------------------------------------------------------
DEBUG in wsshd [/usr/lib/python2.7/site-packages/wssh-0.1.0-py2.7.egg/EGG-INFO/scripts/wsshd:27]:
192.168.1.115 -> aaronwtl@localhost: [interactive shell]
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
ERROR in wsshd [/usr/lib/python2.7/site-packages/wssh-0.1.0-py2.7.egg/EGG-INFO/scripts/wsshd:47]:
Error while connecting to localhost: from_buffer() cannot return the address of the raw string within a str or unicode or bytearray object
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/wssh-0.1.0-py2.7.egg/EGG-INFO/scripts/wsshd", line 44, in connect
    allow_agent=app.config.get('WSSH_ALLOW_SSH_AGENT', False))
  File "/usr/lib/python2.7/site-packages/wssh-0.1.0-py2.7.egg/wssh/server.py", line 98, in open
    look_for_keys=False)
  File "/usr/lib/python2.7/site-packages/paramiko/client.py", line 380, in connect
    look_for_keys, gss_auth, gss_kex, gss_deleg_creds, gss_host)
  File "/usr/lib/python2.7/site-packages/paramiko/client.py", line 608, in _auth
    self._transport.auth_password(username, password)
  File "/usr/lib/python2.7/site-packages/paramiko/transport.py", line 1266, in auth_password
    self.auth_handler.auth_password(username, password, my_event)
  File "/usr/lib/python2.7/site-packages/paramiko/auth_handler.py", line 107, in auth_password
    self._request_auth()
  File "/usr/lib/python2.7/site-packages/paramiko/auth_handler.py", line 158, in _request_auth
    self.transport._send_message(m)
  File "/usr/lib/python2.7/site-packages/paramiko/transport.py", line 1587, in _send_message
    self.packetizer.send_message(data)
  File "/usr/lib/python2.7/site-packages/paramiko/packet.py", line 360, in send_message
    out = self.__block_engine_out.update(packet)
  File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/primitives/ciphers/base.py", line 149, in update
    return self._ctx.update(data)
  File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/backends/openssl/ciphers.py", line 120, in update
    n = self.update_into(data, buf)
  File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/backends/openssl/ciphers.py", line 131, in update_into
    "unsigned char *", self._backend._ffi.from_buffer(buf)
TypeError: from_buffer() cannot return the address of the raw string within a str or unicode or bytearray object
^CKeyboardInterrupt
Sun Jan 28 10:07:37 2018
[root@localhost wssh]# wsshd
wsshd/0.1.0 running on 0.0.0.0:5000
--------------------------------------------------------------------------------
DEBUG in wsshd [/usr/lib/python2.7/site-packages/wssh-0.1.0-py2.7.egg/EGG-INFO/scripts/wsshd:27]:
192.168.1.115 -> aaronwtl@localhost: [interactive shell]
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
ERROR in wsshd [/usr/lib/python2.7/site-packages/wssh-0.1.0-py2.7.egg/EGG-INFO/scripts/wsshd:47]:
Error while connecting to localhost: from_buffer() cannot return the address of the raw string within a str or unicode or bytearray object
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/wssh-0.1.0-py2.7.egg/EGG-INFO/scripts/wsshd", line 44, in connect
    allow_agent=app.config.get('WSSH_ALLOW_SSH_AGENT', False))
  File "/usr/lib/python2.7/site-packages/wssh-0.1.0-py2.7.egg/wssh/server.py", line 98, in open
    look_for_keys=False)
  File "/usr/lib/python2.7/site-packages/paramiko/client.py", line 380, in connect
    look_for_keys, gss_auth, gss_kex, gss_deleg_creds, gss_host)
  File "/usr/lib/python2.7/site-packages/paramiko/client.py", line 608, in _auth
    self._transport.auth_password(username, password)
  File "/usr/lib/python2.7/site-packages/paramiko/transport.py", line 1266, in auth_password
    self.auth_handler.auth_password(username, password, my_event)
  File "/usr/lib/python2.7/site-packages/paramiko/auth_handler.py", line 107, in auth_password
    self._request_auth()
  File "/usr/lib/python2.7/site-packages/paramiko/auth_handler.py", line 158, in _request_auth
    self.transport._send_message(m)
  File "/usr/lib/python2.7/site-packages/paramiko/transport.py", line 1587, in _send_message
    self.packetizer.send_message(data)
  File "/usr/lib/python2.7/site-packages/paramiko/packet.py", line 360, in send_message
    out = self.__block_engine_out.update(packet)
  File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/primitives/ciphers/base.py", line 149, in update
    return self._ctx.update(data)
  File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/backends/openssl/ciphers.py", line 120, in update
    n = self.update_into(data, buf)
  File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/backends/openssl/ciphers.py", line 131, in update_into
    "unsigned char *", self._backend._ffi.from_buffer(buf)
TypeError: from_buffer() cannot return the address of the raw string within a str or unicode or bytearray object

**Comment by huashengdun** [comment]
Is this project still under maintenance?
